version: '3'

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000

  experiment:
    build: .
    depends_on:
      - mlflow
    volumes:
      - ./:/mlflow_project
      - ./data:/mlflow_project/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    working_dir: /mlflow_project
    command: python src/main.py --data_path ./data/har.csv